on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Release
jobs:
  Release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Release
        uses: huggingface/semver-release-action@latest
