on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Test and coverage

env:
  LATEST_GO_VERSION: "1.21"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.LATEST_GO_VERSION }}
          check-latest: true
      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}